### ISSUE TITLE
If you destroy the crystal with the stone of destruction, the screen turns black and you fall down

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#1]
If you destroy the crystal with the stone of destruction, the screen turns black and nothing else happens. If I press F5, I can see my Y coordinate decrease, meaning I fall down.

Tested in the Game Jam version.

**Comment by Irevol** [comment]
Fixed
*sigh* so many bugs
Thanks for reporting them all, I'll fix the game breaking ones and leave the rest until after the jam.
