### ISSUE TITLE
HUDs too big

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#10]
I'm playing on a 1366x768 display, with HUD scaling set to 1.25 to make hotbars and such large enough to see.  When the title displays after exiting the "prologue" maze, it just says "ITAD".

I don't think it's possible to figure out a player's scaling options, so you may have to either make assumptions that it's below some reasonable limit like 1.5x or 2x, or use only "stretch to fit screen" HUDs.  As of at least the latest MT version, you should be able to get the player's client window resolution, which you can use to either statically size HUDs, or use [combine to add padding to match the image to the window aspect ratio so that you can stretch it without distortion.

**Comment by Irevol** [comment]
Yikes, I didn't think about that at all. 
I'll work on that.

**Comment by Wuzzy2** [comment]
Actually, is IS possible to get the player's HUD scaling options with `minetest.get_player_window_information`. :-)

**Comment by Warr1024** [comment]
This has been fixed in 768387b2b6a35fad893d71e0295bc7803b2a3c33, now in main.
