### ISSUE TITLE
Inventory formspec text overflow

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#14]
![screenshot_20231222_122944](https://github.com/Irevol/minetest-citadel/assets/324806/ded01d9b-77e9-40b6-8657-c531b181116a)

Probably needs to be in some kind of element that supports wrapping and/or scrolling, unless you want to make the entire form larger.

Also, considering the number of possible items in the game (and the fact that, even if you somehow encounter another copy of one, there's no reason to allow it to be picked up), it seems like a lot of the screen real estate that's currently used for inventory slots could reasonably be used to fit the text better.

**Comment by Irevol** [comment]
I separated the inventory and tips into 2 pages, the tips page should be big enough to not overflow.
The tips should be replaced with something diegetic in the future anyway.
