### ISSUE TITLE
Crash after rightclicking ghost a second time after destroying crystal

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#19]
Now that the crystal crash is fixed, there is a new one:

1. Destroy the crystal
2. In the new world, rightclick the ghost. It tells you farewell
3. You get teleported back
4. I rightclick the ghost next to the crystal

This crash happens:

```
AsyncErr: Lua: Runtime error from mod 'citadel_core' in callback luaentity_run_simple_callback(): ...uzzy/.minetest/games/citadel/mods/citadel_core/ghost.lua:27: attempt to concatenate a nil value
stack traceback:
	...uzzy/.minetest/games/citadel/mods/citadel_core/ghost.lua:27: in function <...uzzy/.minetest/games/citadel/mods/citadel_core/ghost.lua:22>
```

**Comment by Warr1024** [comment]
There's also a crash when talking to the ghost after reloading the world if you do NOT time travel before talking to the ghost, which may be related.

~~It looks like the ghost saves `self._images` in staticdata (which it probably doesn't need to) but does not save `self._image_index` in staticdata, which is the thing you actually need here~~ nevermind, I was interpreting the meaning of those variables wrong.
