### ISSUE TITLE
Can walk off the map at the beginning

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#2]
At the beginning of the game, you can fall off the map by jumping to the wall from (-8, 9.5, 9) to (-9, 10, 7).

Found in the game jam version.

**Comment by Warr1024** [comment]
Took me a while to figure it out, but confirmed.  You have to jump onto the small tree on the left just after the "jumping from pillar to pillar" parkour section, and then follow the outer wall.

It feels like the long-term solution to this could be rethinking how the "intro" section works entirely (I can't tell what it adds to the game).  In the short term, the schematics could just be fixed to raise the walls ... though adding invisible barriers around the entire map to prevent "leaks" would be a more thorough solution.

Tbf, while I don't see a way to get through it, this break in the Southeast corner wall is similarly distracting.

![screenshot_20231226_202652](https://github.com/Irevol/minetest-citadel/assets/324806/5ab597af-b350-4c40-9e1c-cb69c256dd5a)

**Comment by andyca111100** [comment]
Also achievable by using an acorn or bamboo shoot (You can place them under your feet. I am not sure if placing plants not on the ground is a bug or a feature)
