### ISSUE TITLE
Suggestion: Consider removing the inventory interface

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#24]
As far as I can tell, the game contains only:

- 4 stones
- 4 plant seeds/sprouts
- 7 bonus items

Since the bonus items don't actually do anything, there's no need to ever have them in your hotbar, so you could use a separate HUD somewhere to display their status.  (I might just do something like draw non-selectable icons for them somewhere else on the screen)

That leaves only 6 items you could potentially need to have in the hotbar.  There's no need for the remainder of the inventory, and the inventory screen then becomes only necessary for reordering them.

There's also no reason why the items need to be able to be custom-ordered.  For a list that short, it's also quite reasonable to statically assign each one to a position in the hotbar (making hotkeys always consistent between game instances).

Thus, with a few changes to the way the inventory is managed, it's possible to simplify the interface and remove this unnecessary piece of surface area, making the game design more focused.  The "inventory" form can then become just the hint text, until you find a way to work that into the game world too, or you could put some "About" or version/debugging info there, or a custom achievement/treasure list or something.

**Comment by Irevol** [comment]
Definitely a good idea. I was thinking of some sort of achievement list.

**Comment by Warr1024** [comment]
From https://github.com/Irevol/minetest-citadel/issues/38#issuecomment-1877650432:

> Maybe there's some way to partition the hotbar into 2 4-slot spaces (1 for stones and 1 for plants), and then move a stone/plant to the correct area when you pick it up.

Having each item have "assigned slots" in the hotbar is not super hard; I may take a look at that one myself.

Rather than "partitioning" the hotbar, I was thinking that, since the "treasures" are not actually "usable" items, rather than showing them in the hotbar at all, I'd use custom image HUDs for them.  I might also take a shot at this one myself.

The last thing to do is to add a text HUD that displays the name of items, if you want item names to be in the game at all (it's a valid choice to just never display names, which saves you potential translation work, but can also make it a bit harder for players to have coherent discussions without official names).  That's easy enough to do for the wielded items in the hotbar ... for the treasures, players would only really have an opportunity to see the name once, when they first acquire the item.
