### ISSUE TITLE
Inventory "Tips" tab STILL doesn't fit

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#25]
#14 is still not fixed.

I think the problem is that you are using **labels** which do not handle overflow or wrapping.  You should switch to using a **textarea** (how I solved this exact problem in NodeCore) which does all that automatically.

It's not certain that diagetic guidance will fully replace this interface (you may still want to have things like support contact info, version info, etc on this screen), so it's probably still a good idea to get this fixed.

![screenshot_20231223_160815](https://github.com/Irevol/minetest-citadel/assets/324806/ac995a31-0ba1-4cf5-9384-a42eaaabfb76)

**Comment by Irevol** [comment]
I would like some sort of guidance system to completely replace this interface... support info can be on contentdb, version info could be in a hud in the corner.

**Comment by Irevol** [comment]
I didn't realize you could use textarea as a multi-line label, I thought it was just for input... thanks for pointing that out.
