### ISSUE TITLE
You can nerdpole with 2 nodes by placing them on top of each other

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#3]
If you have two placable nodes (acorn, big acorn or bamboo sprout), you can place them on top of each other to have ground to stand on.

If you build a tower of two nodes, you can nerdpole all the way to the top. First you build the 2-node tower, then you jump on it, then you sneak to the side of the top so that you can dig the bottom node which you can place again on the top.

I'm pretty sure this is not intended. ;-)

Found in the Game jam version.

**Comment by Irevol** [comment]
Fixed, you can no longer place plants on top of breakable nodes.
