### ISSUE TITLE
Stones can get stuck in "active" state

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#35]
If you quit the game while a stone is still "active" and glowing, it will be stuck permanently in the "active" glowing state and cannot be used.

This is because the stone is replaced by the active version when used, and then restored back to its usable state by a minetest.after scheduled job, but those are not preserved across reloads.

**Comment by andyca111100** [comment]
![зображення](https://github.com/Irevol/minetest-citadel/assets/113429882/2a6c2ea1-fea5-40b9-b6f4-c971bfa6d401)

not really completed I guess
