### ISSUE TITLE
Sometimes, nodes (artifacts, seeds) get duplicated on timetravel

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#4]
Sometimes, the placable nodes (artifacs and seeds) get duplicated when you timetravel. I haven't really figured out what exactly triggers this tho. For example, I could theoretically get infinite acorns. No idea if this is intentional.

Found in the game jam version.

**Comment by Irevol** [comment]
Strange... I can't replicate this, perhaps you can provide some more details?

**Comment by Warr1024** [comment]
I ran into this too.

I saw this happen almost always with the "bonus" items.  If I picked up the item and then traveled to a different time period, very often the item would be there, especially something like the minetest-logo item which existed across time, and so I could pick it up in the future, travel to the past before I picked it up, and then pick it up again (it's fun carrying a paradox in your inventory).

The acorns for the MOST part behaved better, but I noticed after having cheesed my way on top of the tower, then exploring the post-game more, then remembering that I had left them up there and going to pick them up, when I was later exploring more, trees had grown on top of one another up on the tower, and when I traveled back in time the acorns were back and duplicated.

**Comment by Warr1024** [comment]
Piranesi Restoration has a system with similar purpose, keeping track of changes that have happened to rooms that are not currently loaded, to apply them when the room is loaded.  It similarly had a lot of subtle bugs that took a long time to work out, but it HAS been possible to work them all out eventually.

If https://github.com/minetest/minetest/pull/14126 ends up getting merged for 5.9, though, it may be possible to implement games like Citadel and Piranesi in a completely different way, which may make map change tracking much simpler.

**Comment by Irevol** [comment]
Thanks for the advice, I'll work on it.
