### ISSUE TITLE
Resume CDB Releases 

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#41]
CDB releases had to be "frozen" for the jam rating period.  That is now over, so jam games can resume regular releases, and Citadel has a lot of improvements since the jam version, and it would be good to get those exposed to the community, and prevent bug reports coming in from old versions where the issues were already fixed.

Ideally, enable the automatic releases feature on CDB and let it make daily releases if there is any change in the main branch.  Unless you want to run your own CI.

**Comment by Irevol** [comment]
I made a new release and enabled automatic releases.
