### ISSUE TITLE
Dialogue fills entire screen

### ISSUE THREAD

**Issue by regulus79** [Irevol/minetest-citadel#42]
When the dialogue appears after rightclicking the ghost, it fills my entire screen. I believe that Nathan.S's review of the game had the dialogue small in the center of the screen.
![image](https://github.com/Irevol/minetest-citadel/assets/117475203/bb57b948-b5c0-4939-930d-8c89c0b62778)
I am unsure whether this was intentional or not; if it was intentional, then I suppose this issue should be closed. (sorry for wasting you time lol)

**Comment by Irevol** [comment]
Don't be sorry! However, this is intentional. Older versions did indeed have a smaller dialogue hud, but full-screen dialogue ensures readability on all screen sizes.
