### ISSUE TITLE
It's possible to see two ghosts at the same time

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#49]
![screenshot_20240108_094341](https://github.com/Irevol/minetest-citadel/assets/324806/71e785d2-e776-43f3-80aa-5157fd05960e)

Oops.

I assumed that you were supposed to only ever see at most one at a time, so that it creates the illusion that the ghost is just moving around ... but this kind of spoils the illusion.

Since both ghosts are very likely _active_ at the same time, you can probably work around this by making ghost opacity variable.  For consistency, you could make them all fade out based on distance ... for consistency, based on a threshold, or to handle just this one case, based on whether they are the closest ghost or not.

**Comment by Irevol** [comment]
Or just move one of them so you can't see both at once...   I like the idea of making the farther ghost fade out but there's that engine bug.
