### ISSUE TITLE
Not enough space in the inventory

### ISSUE THREAD

**Issue by andyca111100** [Irevol/minetest-citadel#50]
There are only 8 slots for inventory, but in fact 10 are needed (a letter, a journal, 4 stones, and 4 plants).
Because of this, everything that comes after the 8th item in the inventory technically disappears.

**Comment by Irevol** [comment]
oops

**Comment by Irevol** [comment]
I don't know how I didn't catch such a game-breaking thing...  better go add a release on contentdb real quick

**Comment by Kimapr** [comment]
![image](https://github.com/Irevol/minetest-citadel/assets/50977029/3e0873d4-0611-464a-88a9-23d35bd016ea)
I ran out of space after a dupe glitch...
