### ISSUE TITLE
Chat spaces for the game

### ISSUE THREAD

**Issue by Warr1024** [Irevol/minetest-citadel#54]
Are there any non-long-form discussion spaces for the game, like chatrooms like IRC, Matrix or Discord?  I only see GitHub and the Forum topic, which are really only good for formal and/or long-form communication.

If you have some, or create some, it would be good to scatter links around, like in the README, CDB description, and somewhere in the game like an About screen, credits screen, or tutorial content.

If you don't intend to ever create any, I'd like to know, as I might be interested in running an unofficial fan space for it myself.

**Comment by Irevol** [comment]
I've set up [discord](https://discord.gg/HQpacNUvDJ) and [matrix](https://matrix.to/#/#citadel-minetest:matrix.org)
Thanks for all the interest, I never would have guessed there would be any sort of demand for community spaces.
