### ISSUE TITLE
You can get big acorn without stone of unbarring

### ISSUE THREAD

**Issue by Wuzzy2** [Irevol/minetest-citadel#9]
You can the get big acorn without stone of unbarring. I don't know if this is by design or an oversight.

If I grow a normal acorn close to where the bars would be, they destory the dirt and I can bypass the metal bars in the future.

**Comment by Irevol** [comment]
Originally I intended for plants that have their "source node" overlapped with another node when time traveling to not grow (if that makes sense) which would make stuff like this impossible.
However, I kind of like how you can bypass the bars with a little experimentation. Receiving the big acorn early shouldn't be a problem.
Regardless, I'll probably end up fixing it anyway.
